// app/layout.tsx
import './globals.css';

import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

import { OurProvider } from './OurProvider';

export const metadata: Metadata = {
  title: 'D and I',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" />
        <OurProvider>{children}</OurProvider>
      </body>
    </html>
  );
}
